# Generated by Django 5.0.3 on 2024-03-20 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IndexInfo",
            fields=[
                (
                    "ts_code",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=50)),
                ("fullname", models.CharField(max_length=100)),
                ("market", models.CharField(max_length=20)),
                ("publisher", models.CharField(max_length=50)),
                ("index_type", models.CharField(max_length=20)),
                ("category", models.CharField(max_length=20)),
                ("base_date", models.DateField()),
                ("base_point", models.FloatField()),
                ("list_date", models.DateField()),
                ("weight_rule", models.CharField(max_length=50)),
                ("desc", models.TextField(blank=True)),
                ("exp_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "指数基本信息",
                "verbose_name_plural": "指数基本信息",
            },
        ),
        migrations.CreateModel(
            name="StockInfo",
            fields=[
                (
                    "ts_code",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("symbol", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=50)),
                ("area", models.CharField(max_length=50)),
                ("industry", models.CharField(max_length=50)),
                ("fullname", models.CharField(max_length=100)),
                ("enname", models.CharField(blank=True, max_length=100)),
                ("cnspell", models.CharField(blank=True, max_length=20)),
                ("market", models.CharField(max_length=10)),
                ("exchange", models.CharField(max_length=10)),
                ("curr_type", models.CharField(max_length=10)),
                ("list_status", models.CharField(max_length=1)),
                ("list_date", models.DateField()),
                ("delist_date", models.DateField(blank=True, null=True)),
                ("is_hs", models.CharField(max_length=1)),
                ("act_name", models.CharField(blank=True, max_length=100)),
                ("act_ent_type", models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="IndexComponentWeight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index_code", models.CharField(max_length=20)),
                ("con_code", models.CharField(max_length=20)),
                ("trade_date", models.DateField()),
                ("weight", models.FloatField()),
            ],
            options={
                "verbose_name": "指数成分股权重",
                "verbose_name_plural": "指数成分股权重",
                "unique_together": {("index_code", "con_code", "trade_date")},
            },
        ),
        migrations.CreateModel(
            name="IndexDaily",
            fields=[
                (
                    "ts_code",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("trade_date", models.DateField()),
                ("close", models.FloatField()),
                ("open", models.FloatField()),
                ("high", models.FloatField()),
                ("low", models.FloatField()),
                ("pre_close", models.FloatField(blank=True, null=True)),
                ("change", models.FloatField(blank=True, null=True)),
                ("pct_chg", models.FloatField(blank=True, null=True)),
                ("vol", models.FloatField(blank=True, null=True)),
                ("amount", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "指数日线行情",
                "verbose_name_plural": "指数日线行情",
                "unique_together": {("ts_code", "trade_date")},
            },
        ),
        migrations.CreateModel(
            name="StockDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trade_date", models.DateField()),
                ("open", models.FloatField()),
                ("high", models.FloatField()),
                ("low", models.FloatField()),
                ("close", models.FloatField()),
                ("pre_close", models.FloatField()),
                ("change", models.FloatField()),
                ("pct_chg", models.FloatField()),
                ("vol", models.FloatField()),
                ("amount", models.FloatField()),
                (
                    "ts_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="domestic.stockinfo",
                    ),
                ),
            ],
            options={
                "unique_together": {("ts_code", "trade_date")},
            },
        ),
    ]
