# Generated by Django 5.0.3 on 2024-04-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexDaily',
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ('ts_code', models.CharField(max_length=20, serialize=False)),
                ('trade_date', models.DateField()),
                ('close', models.FloatField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('pre_close', models.FloatField(blank=True, null=True)),
                ('change', models.FloatField(blank=True, null=True)),
                ('pct_chg', models.FloatField(blank=True, null=True)),
                ('vol', models.FloatField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '指数日线行情',
                'verbose_name_plural': '指数日线行情',
                'unique_together': {('ts_code', 'trade_date')},
            },
        ),
    ]
