# Generated by Django 5.0.3 on 2024-04-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic', '0002s_indexdaily'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexdaily',
            name='ts_code',
            field=models.CharField(max_length=20),
        ),
    ]
