# Generated by Django 5.0.3 on 2024-04-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic', '0003_alter_indexdaily_ts_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundHoldings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_code', models.CharField(max_length=20)),
                ('ann_date', models.CharField(max_length=20)),
                ('end_date', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=20)),
                ('mkv', models.FloatField()),
                ('amount', models.FloatField()),
                ('stk_mkv_ratio', models.FloatField()),
                ('stk_float_ratio', models.FloatField()),
            ],
            options={
                'verbose_name': '公募基金持仓信息',
                'verbose_name_plural': '公募基金持仓信息',
            },
        ),
        migrations.CreateModel(
            name='FundInfo',
            fields=[
                ('ts_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('management', models.CharField(blank=True, max_length=100)),
                ('custodian', models.CharField(blank=True, max_length=100)),
                ('fund_type', models.CharField(blank=True, max_length=50)),
                ('found_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('list_date', models.DateField(blank=True, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('delist_date', models.DateField(blank=True, null=True)),
                ('issue_amount', models.FloatField(blank=True, null=True)),
                ('m_fee', models.FloatField(blank=True, null=True)),
                ('c_fee', models.FloatField(blank=True, null=True)),
                ('duration_year', models.FloatField(blank=True, null=True)),
                ('p_value', models.FloatField(blank=True, null=True)),
                ('min_amount', models.FloatField(blank=True, null=True)),
                ('exp_return', models.FloatField(blank=True, null=True)),
                ('benchmark', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('invest_type', models.CharField(blank=True, max_length=50)),
                ('type', models.CharField(blank=True, max_length=50)),
                ('trustee', models.CharField(blank=True, max_length=100)),
                ('purc_startdate', models.DateField(blank=True, null=True)),
                ('redm_startdate', models.DateField(blank=True, null=True)),
                ('market', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': '公募基金基本信息',
                'verbose_name_plural': '公募基金基本信息',
            },
        ),
        migrations.CreateModel(
            name='FundManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_code', models.CharField(max_length=20)),
                ('ann_date', models.DateField()),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('birth_year', models.CharField(max_length=4)),
                ('edu', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=20)),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField()),
                ('resume', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': '公募基金基金经理',
                'verbose_name_plural': '公募基金基金经理',
            },
        ),
        migrations.CreateModel(
            name='FundNav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_code', models.CharField(max_length=20)),
                ('ann_date', models.DateField(blank=True, null=True)),
                ('nav_date', models.DateField(blank=True, null=True)),
                ('unit_nav', models.FloatField(blank=True, null=True)),
                ('accum_nav', models.FloatField(blank=True, null=True)),
                ('accum_div', models.FloatField(blank=True, null=True)),
                ('net_asset', models.FloatField(blank=True, null=True)),
                ('total_netasset', models.FloatField(blank=True, null=True)),
                ('adj_nav', models.FloatField(blank=True, null=True)),
                ('update_flag', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name': '公募基金净值',
                'verbose_name_plural': '公募基金净值',
            },
        ),
        migrations.AddConstraint(
            model_name='fundholdings',
            constraint=models.UniqueConstraint(fields=('ts_code', 'ann_date', 'symbol'), name='unique_fund_holdings'),
        ),
        migrations.AddConstraint(
            model_name='fundnav',
            constraint=models.UniqueConstraint(fields=('ts_code', 'nav_date'), name='unique_fund_nav'),
        ),
    ]
