# Generated by Django 5.0.3 on 2024-04-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic', '0004_fundholdings_fundinfo_fundmanager_fundnav_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexcomponentweight',
            name='con_name',
            field=models.CharField(default='none'),
            preserve_default=False,
        ),
    ]
