# Generated by Django 5.0.3 on 2024-04-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic', '0006_stockinfo_index_component_weights_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinfo',
            name='act_ent_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='act_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
