# Generated by Django 5.0.3 on 2024-04-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic', '0007_alter_stockinfo_act_ent_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinfo',
            name='area',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='enname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='fullname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='industry',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
